# Generated by Django 4.1.7 on 2023-03-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentaLibre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='articulo',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.TextField(max_length=40),
        ),
    ]
